!-- parameter get from .env.db-geo
spring.datasource.url=jdbc:mysql://jvdb-geo:3306/mondial
spring.datasource.username=mondial
spring.datasource.password=S3rv3r-GEO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.address=0.0.0.0
server.port=8080

# Imposta il formato predefinito per le date
spring.jackson.date-format=dd/MM/yyyy HH:mm:ss
# Imposta il locale in italiano per la serializzazione JSON
spring.jackson.locale=it_IT
# Forza l'uso del fuso orario corretto
spring.jackson.time-zone=Europe/Rome

# Formato per i log in console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}.%method\\(\\) - %msg%n

# Formato per i log su file (se attivo)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}.%method\\(\\) - %msg%n